# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_hcd" "firewire_ohci" "usb_storage" "usbhid" "dm_thin_pool" ];
  boot.kernelModules = [ "kvm-intel" "tun" "virtio" "dm_thin_pool" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0f1ffb0f-2b9c-4b91-a454-236fa4ecd696";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8BD2-1A71";
      fsType = "vfat";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/27b34a8a-0ef0-45a3-a6a7-fa66c432eb03";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = 12;
}
